baseURL = "http://www.epauler.fr/"
languageCode = "fr"
title = "Ã©pauler.fr"
defaultContentLanguage = 'fr'
description = """
"Des nains sur des Ã©paules de gÃ©ants" Bernard de Chartres

Data, climat, sports, congÃ© paternitÃ©
"""
theme = "anatole-polomarcus"
enableEmoji = true
summarylength = 10
[menu]

  [[menu.main]]
  name = "Ã‰paulons-nous"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "ðŸ“– Articles"
  weight = 300
  identifier = "articles"
  url = "/article/"  

  [[menu.main]]
  name = "ðŸ“º Presse"
  weight = 350
  identifier = "presse"
  url = "/presse/"  

  [[menu.main]]
  name = "ðŸ”— Mes ressources"
  weight = 400
  identifier = "ressources"
  url = "/mes_ressources/"  

  [[menu.main]]
  name = "ðŸ›¢ï¸ Calculer son empreinte carbone"
  weight = 500
  identifier = "nosgestesclimat"
  url = "https://nosgestesclimat.fr/"

[author]
  name = "Paul Leclercq"
  
[params]
title = "Paul Leclercq ðŸ¦•"
author = "Paul Leclercq ðŸ¦•"
description = """
"Des nains sur des Ã©paules de gÃ©ants" 
Bernard de Chartres

Data, climat, sports, congÃ© paternitÃ©"""
copyright = "Copyleft (ðŸ„¯) - CC-BY-SA"

mainSections = [] # content/_index.md default -> https://github.com/lxndrblz/anatole/wiki/%F0%9F%93%84-Content-Settings#using-a-static-page-as-your-home-page

profilePicture = "https://avatars.githubusercontent.com/u/4059615?v=4"
customCss = ["css/custom.css"]
gtagId = "G-W1N7B2KENY"
favicon = "favicons/"
#displayMode = "dark"
contentratio = 0.78
singleDateFormat = "02/01/2006"
indexDateFormat = "02/01/2006"
listDateFormat = "02/01/2006"

postSectionName = "article"
readMore = true

params.assets.disableFingerprinting = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    
[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/polomarcus/blog"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/paleclercq/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/polomarcus"
[[params.socialIcons]]
icon = "fab fa-medium"
title = "Medium"
url = "https://medium.com/@polomarcus"

